name: aws-deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: Configure AWS credentials from IAM
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: upload AWS S3
        run: |
          aws s3 sync ./public s3://aws-s3-serverless/marketchart --delete
          aws s3 cp ./public/index.html s3://aws-s3-serverless/marketchart/index.html --cache-control "no-cache"
